#
# Module manifest for module 'Deploymentor'
#
# Generated by: Nabil Redmann (BananaAcid)
#
# Generated on: 03.04.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Deploymentor.psm1'

# Version number of this module.
ModuleVersion = '1.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = '87cd668c-82e8-4664-ba9a-4e655ef21c10'

# Author of this module
Author = 'Nabil Redmann (BananaAcid)'

# Company or vendor of this module
CompanyName = 'Nabil Redmann'

# Copyright statement for this module
Copyright = '(c) Nabil Redmann (BananaAcid). All rights reserved.'

# Description of the functionality provided by this module
Description = 'A full PowerShell installation helper GUI - fully configurable and simple / quick to use for roll outs 🤖'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Start-Deploymentor'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = '.gitignore', 'Deploymentor.psd1', 'Deploymentor.psm1', 'LICENSE', 
               'README.md', 'actions\_scripted actions go here', 
               'data\_UI files and logic goes here', 'data\config.ps1', 
               'data\default-app.png', 'deploymentor-example.cmd', 
               'deploymentor-example.ps1', 'deploymentor.cmd', 'deploymentor.ps1', 
               'examples\actions\Action Minimal.ps1', 
               'examples\actions\_scripted actions go here', 
               'examples\actions\add admin groups.ps1', 
               'examples\actions\add user as admin.ps1', 
               'examples\actions\admin privileges required.ps1', 
               'examples\actions\disable iv6.ps1', 
               'examples\actions\install dell bios patch and restart.ps1', 
               'examples\actions\msg plug cable.ps1', 
               'examples\actions\open cumputername dialog.ps1', 
               'examples\actions\remove admin user.ps1', 
               'examples\actions\remove default apps.ps1', 
               'examples\actions\remove unneded c dirs.ps1', 
               'examples\actions\require admin by dialog.ps1', 
               'examples\actions\require admin.ps1', 
               'examples\actions\restart with admin privileges.ps1', 
               'examples\actions\run telemetry tool.ps1', 
               'examples\actions\service files patch.ps1', 
               'examples\actions\service files\dummy.txt', 
               'examples\actions\set important env.ps1', 
               'examples\actions\set new Administrator PW.ps1', 
               'examples\actions\show message.ps1', 'examples\data\config.ps1', 
               'examples\data\default-app.png', 
               'examples\profiles\MainLocation.ps1', 
               'examples\profiles\any PS1 here will define a list of software an actions to be in the lists', 
               'examples\profiles\location one.ps1', 
               'examples\profiles\location two.ps1', 
               'examples\software\7Zip\install.ps1', 
               'examples\software\AcrobatReader\install.ps1', 
               'examples\software\BIOS\install.ps1', 
               'examples\software\HardCopy (free)\Einstellungen verteilen - sichern - wiederherstellen.url', 
               'examples\software\HardCopy (free)\hardcopy_config.ini', 
               'examples\software\HardCopy (free)\install.ps1', 
               'examples\software\OOSU10\export.cfg', 
               'examples\software\OOSU10\install.ps1', 
               'examples\software\_any software or just a PS1 install script to call a network file goes here in its folder with an install.ps1 file', 
               'examples\software\dump direct\deploy.ps1', 
               'examples\software\empty\nothing.txt', 
               'examples\software\hello world\deploy.vbs', 
               'examples\tools\ADD to RUN ONCE.ps1', 
               'examples\tools\Networkconnections.lnk', 
               'examples\tools\SystemPropertiesComputerName.lnk', 
               'examples\tools\_.anything here will be added as button (PS1, msc, exe, txt, ...)', 
               'examples\tools\dump ctx.lastActionRet.x.ps1', 
               'examples\tools\lusrmgr.msc.lnk', 'examples\tools\test waiting.ps1', 
               'examples\tools\test waiting.x.ps1', 
               'profiles\any PS1 here will define a list of software an actions to be in the lists', 
               'publish.ps1', 
               'software\_any software or just a PS1 install script to call a network file goes here in its folder with an install.ps1 file', 
               'tools\_.anything here will be added as button (PS1, msc, exe, txt, ...)', 
               'window\App.config', 'window\App.xaml', 'window\App.xaml.cs', 
               'window\DeploymentorUI.csproj', 'window\DeploymentorUI.sln', 
               'window\MainWindow.xaml', 'window\MainWindow.xaml.cs', 
               'window\Properties\AssemblyInfo.cs', 
               'window\Properties\Resources.Designer.cs', 
               'window\Properties\Resources.resx', 
               'window\Properties\Settings.Designer.cs', 
               'window\Properties\Settings.settings', 'window\default-app.png'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'deployment','gui','rollout','utility','tools','installation'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/BananaAcid/Deploymentor/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/BananaAcid/Deploymentor'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/BananaAcid/Deploymentor'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

