[Settings]

;	R1 S1 (PRINT) = Druck --> Rechteck
V011=1362

;	Hardcopy-Fenster �ffnen
V012=64

;	R2 S1 (ALT+PRINT) = Alt+Druck --> keine Funktion
V013=1359

;	Druckersymbol linke Taste --> keine Funktion
V015=1359

;	System Tray --> Rechteck
V021=1362

;	Hardcopy-Fenster �ffnen
V022=64

;	R2 S2 (STRG+PRINT) = Strg+Druck --> keine Funktion
V029=1359

;	Frage stellen "Hardcopy beenden?": 0=nein, 1=ja
V136=0

;	Hardcopy beenden oder minimieren: 0=minimieren, 1=beenden
V137=0

;	Einstellungen -> Optionen -> Druckersymbol, Tabelle Zeile 1
V1114=\office15\*.exe
V1115=1
V1116=-70
V1117=0
V1118=0

;	Einstellungen -> Optionen -> Druckersymbol, Tabelle Zeile 2
V1119=\office16\*.exe
V1120=1
V1121=-110
V1122=0
V1123=0

;	Letztes Verzeichnis �ffnen/Sichern "Einstellungen"
V1238=C:\Users\Public\files\Hardcopy
